### PR TITLE
Fix sed error

### PR DESCRIPTION
**Pull request by Pro-pra**

### CODE REVIEW

**Comment by markjcrane** [comment]
After you signup as a contributor I will accept both of your pull requests.

**Comment by Pro-pra** [comment]
CLA mail sent

signed.

**Comment by Pro-pra** [comment]
contributor info pull request sent.

**Comment by Pro-pra** [comment]
yes, you right.

**Comment by markjcrane** [comment]
The password isn't working right still so will work on resolving it your atempt to fix it was still appreciated.

**Pull request closed without merging**
