### PR TITLE
Enhance-Firewall tweaks

### PR DESCRIPTION
**Pull request by mafoo**
reinstate sip chain to allow bot dropping for unencrypted traffic

### CODE REVIEW

**Comment by markjcrane** [comment]
I havn't excepted this as I don't see the benefit of moving the the rules into the 'sip' chain.

**Comment by mafoo** [comment]
The advantage of a separate chain is it means you only require one rule per bot rather than 4 per bot so it makes maintenance easier.
If we go down this route it also makes it possible to consider a inbuilt app in fusion itself to manage the bot rules (as it could safely wipe and recreate the chain)

**Comment by tomgillett** [comment]
I realise that this is entirely unsupported, but I've spent some time attempting to make FreeSWITCH / FusionPBX run nicely in Docker containers. Best practice here is to use a container-per-component approach. I've had to do a little bit of fiddling in the FusionPBX source to make it work but so far, so good.

> If we go down this route it also makes it possible to consider a inbuilt app in fusion itself to manage the bot rules (as it could safely wipe and recreate the chain)

Whilst I don't have a strong opinion on a separate "SIP" chain, the idea of allowing FusionPBX to manage its own firewall rules seems to entrench the "all on one box" approach. An assumption that FusionPBX can control its own firewall would make it impossible to run within Docker.

Just another $0.02 :)

**Comment by DigiDaz** [comment]
Tom,

Not necessarily, the FusionPBX instance could still control the rules on a different system. We just mentioned that currently if a new profile is created, it remains totally unprotected. Maybe it could even be an option to enable/disable.

**Comment by markjcrane** [comment]
I think the answer is still vague.

**Comment by mafoo** [comment]
although it is a limited form of blocking it is still effective at dropping most of the bot traffic as scammers generally are of the script kiddie variety that don't have a clue about what they are running other than it gives them money/calls. I agree this is not a end solution but it is a tool in an arsenal to cut the wheat from the chaff to make it easier to spot bad calls. Anyone that is proficient at hacking is going to defeat most of the automated steps we can put in place to catch them out, however having the number of calls cut down is going to make it a lot easier to spot calls that need a human to analyze

**Pull request closed without merging**
