### PR TITLE
Ubuntu 20.04

### PR DESCRIPTION
**Pull request by alex-eri**
Bump php version to 7.4, removed libvpx5.

### CODE REVIEW

**Comment by alex-eri** [comment]
scripts directory not installed and cdr not working..

**Comment by markjcrane** [comment]
I would really like to get Ubuntu support improved. Please sign up as a contributor here.
- https://github.com/fusionpbx/open-source

It does look like your commit covers similar ground to also not signed up as a contributor. In an attempt to be fair I'll give him a chance to sign up as a contributor if he doesn't and you do I'll accept your pull request. If there are additional changes that you see then I'll accept your future pull request. However we do need to improve the situation for Ubuntu so will be taking action on this in a few days regardless.
https://github.com/fusionpbx/fusionpbx-install.sh/pull/363

**Comment by alex-eri** [comment]
There is some new problems. Freeswitch no installable without backporting some libs.

**Comment by alex-eri** [comment]
I think rewriting for new and drop old releases needed.

ps. I will sign it later.

**Comment by alex-eri** [comment]
> The reason they are separate is if any command were to fail it wouldn't be as catastrophic. With this change If one of these were to fail all will fail. Is that the desired behavior?

If one of this failed - build failed at source configuration.

**Comment by seanvandermolen** [comment]
Fresh install on 20.04

switch/source-release.sh: 39: pushd: not found
switch/source-release.sh: 58: ./configure: not found
switch/source-release.sh: 63: make: not found
switch/source-release.sh: 67: make: not found
switch/source-release.sh: 68: make: not found
switch/source-release.sh: 69: make: not found
switch/source-release.sh: 70: make: not found
switch/source-release.sh: 72: popd: not found
mv: cannot stat '/usr/share/freeswitch/sounds/music/*000': No such file or directory
chown: cannot access '/var/lib/freeswitch': No such file or directory
chown: cannot access '/var/log/freeswitch': No such file or directory

E: Unable to locate package freeswitch-systemd
Job for freeswitch.service failed because the control process exited with error code.
See "systemctl status freeswitch.service" and "journalctl -xe" for details.


Install on 18.04 mini

PHP-FPM socket in nginx is pathed to 7.4 when 7.2 is installed

Similar issue to 20.04 where freeswitch never finishes it's install and the service fails to load.  


Debian 10


E: Unable to locate package libyuv-dev
mv: cannot move '/usr/share/freeswitch/sounds/music/default/16000' to '/usr/share/freeswitch/sounds/temp/16000': Directory not empty
mv: cannot move '/usr/share/freeswitch/sounds/music/default/32000' to '/usr/share/freeswitch/sounds/temp/32000': Directory not empty
mv: cannot move '/usr/share/freeswitch/sounds/music/default/48000' to '/usr/share/freeswitch/sounds/temp/48000': Directory not empty
mv: cannot move '/usr/share/freeswitch/sounds/music/default/8000' to '/usr/share/freeswitch/sounds/temp/8000': Directory not empty

**Comment by markjcrane** [comment]
Ubuntu 20.04 install script is now working with FreeSWITCH 1.10.3

**Pull request merged**
