### PR TITLE
Fix to issue #60 - login failed when install.sh runs multiple times (…

### PR DESCRIPTION
**Pull request by erxspin**

### CODE REVIEW

**Comment by erxspin** [comment]
test is passed with Ubuntu 16.04 amd64
test is passed with Debian 8.7 amd64

**Comment by markjcrane** [comment]
Please explain this in better detail.

**Comment by erxspin** [comment]
If you run script ./install.sh multiple times in same box with different command lines switches then script will insert multiple rows in v_domains, v_users tables in fusionpbx db.

	domain_uuid	|	domain_parent_uuid	|	domain_name	|	domain_enabled	|	domain_description	|
	1303fe38-f3d6-4fea-8486-cd0eb3b751e4	|	-	|	ip.add.re.ss	|	true	|	-	|
	32af4924-c7e0-4f93-97f8-b65cd755ad69	|	-	|	ip.add.re.ss	|	true	|	-	|
	530ab595-5672-4eb2-9925-3d4c6724afbd	|	-	|	ip.add.re.ss	|	true	|	-	|
	5e1708aa-b125-4176-bc0c-76102a1bbe0f	|	-	|	ip.add.re.ss	|	true	|	-	|
	6bc8bf10-b091-4772-8649-f5b783d097de	|	-	|	ip.add.re.ss	|	true	|	-	|
	77f2a421-eef4-44a3-ba33-9b476d3987d0	|	-	|	ip.add.re.ss	|	true	|	-	|
	a7796a75-b461-4241-882c-1cf9fa8d5bc3	|	-	|	ip.add.re.ss	|	true	|	-	|
	d31eb919-764b-432f-bb03-faab6566af08	|	-	|	ip.add.re.ss	|	true	|	-	|
	ef2957e5-2756-4e1e-a125-88de1fb4f42e	|	-	|	ip.add.re.ss	|	true	|	-	|
	fa25ad11-31aa-4b8e-b284-a49b9f7d0f09	|	-	|	ip.add.re.ss	|	true	|	-	|
	
(10 rows)

That is why login to fusionpbx web interface will fail even with right password for 'admin' account.

It can be done with following sequence, for example.
Commands may be executed in different consoles by mistake or not.

``
./install.sh
``
``
./install.sh --help
``
``
./install.sh --use-switch-master
``

**Comment by markjcrane** [comment]
I realized it tried to prevent new duplicate domains I really question the idea of disabling the other domains in I don't think its safe to disable the other domains. Instead if it exists we simply get the domain_uuid of the matching domain and us it. Groups we don't need to add over again. We can add the user again unless there is a matching user in which case we re-use it and reset the password.

**Comment by erxspin** [comment]
Yes, I agree that disabling other domains with same ip address is not safe.

But this disable action will be only triggered if

1) previous versions of install.sh ( without checking ) executed multiple times before
2) there are already multiple domains with same ip address in db

If I had known which domain is correct one then I would be leave exactly this domain enabled.

3) If we leave multiple domains with same ip address in db then almost all logins will fail

Another approach is to not execute but print shell commands with example SQL query that will try to fix this situation in db.

**Comment by markjcrane** [comment]
Your case of duplicate domains with the same name was created by the install script being run multiple times. Therefore we don't need to defend against such a case if the install script re-uses the existing domain rather then adding a duplicate domain then the case you are working to prevent  won't even exist.

**Comment by erxspin** [comment]
Ok, I will split changes into two files

1) "safe" part wth checks will stay in './debian/resources/finish.sh' to prevent such situation with duplicates

2) "not safest one" part with domains disabling will be placed in separate file - may be name it ./debian/resources/fix_duplicates.sh ?

What do you think about this ?

**Comment by erxspin** [comment]
It needs some tests

**Comment by erxspin** [comment]
I will redo commit

**Comment by erxspin** [comment]
Last change is reworked and recommited.
It still needs testing ...

**Comment by Bchudasama** [comment]
Thank you for your responce. 

I tried my above observation last night around 9 pm eastern .
Got a new sd card and changed the pi3 lan ip address to something different and it worked. I dont know when you made changes to the script. but thats what worked for me. 

This is not a commercial box . its something I like to fiddle around. and made my home box.

Thank yo so so much again erxspin.

**Comment by erxspin** [comment]
Not at all !

But I think your situation was different than "multiple domains issue" ...
May be it was connected with php*-fpm and nginx .

**Comment by erxspin** [comment]
Another test with Ubuntu 16.04.x amd64

Duplicate domains are detected successfully and example command to fix situation are printed to console.

**Comment by erxspin** [comment]
Scripts prints on console

"Found domain_uuid_count = [4]"

but ironically login to fusionpbx web interface is not failed !

May be I am lucky one ... or there is logic in fusionpbx that choose first row from v_domains table in the same way as in changed script lines ...

**Comment by erxspin** [comment]
Another test with Debian 8.x amd64

Script printed

"Found domain_uuid_count = [2]"

Multiple domains are detected as it should.

I think that I just found login failure conditions ... and changed script solved duplication issue again in another install with different db without "disabling" domains.

**Comment by erxspin** [comment]
Login is not failed if first inserted domain_uuid are same that first row that chosen by select result ordered by uuid.

If new row witn generated uuid is placed before first created domain_uuid then login fails.

**Comment by markjcrane** [comment]
Fixed with drop schema public cascade and create schema public added backup script too.

**Pull request closed without merging**
