### PR TITLE
Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by Linutux**
Here is a pull request to support Ubuntu 20.04 with PHP 7.4

### CODE REVIEW

**Comment by Linutux** [comment]
Please don't merge yet, as we have a missing dependancy!

libvpx5 is not available for Ubutu 20.04 focal. It is only available for Ubuntu 18.04 bionic. 

Also we need to install package yasm during install for the freeswitch setup to work.

**Comment by markjcrane** [comment]
I am interested in Ubuntu 20.04 LTS version support so let me know when you feel this is ready.

**Comment by markjcrane** [comment]
Is this ready to merge?

**Comment by alex-eri** [comment]
libvpx-dev depends on right version. Just remove `libvpx5` from script

**Comment by markjcrane** [comment]
I would really like to get Ubuntu support improved. Please sign up as a contributor here.
- https://github.com/fusionpbx/open-source

alex-eri put in a similar pull request but will give you the first chance if you sign up as a contributor. However I really want to get this moving along so please do so if you plan to in the next day or two. Or let us know your intention.

Best Regards, Mark

**Comment by markjcrane** [comment]
Okay accepting the other pull request as he signed the contributor agreement first. Need to make progress on the Ubuntu install.

**Comment by markjcrane** [comment]
Waited a week for you to sign contributor agreement and wanted to move the Ubuntu install forward so accepted alex-eri's pull request.

**Comment by markjcrane** [comment]
Ubuntu 20.04 install script is now working with FreeSWITCH 1.10.3

**Comment by Linutux** [comment]
> Waited a week for you to sign contributor agreement and wanted to move the Ubuntu install forward so accepted alex-eri's pull request. Sorry I should have asked you to sign it early on when you first made your pull request.

No problem. I don't have that much spare time at the moment. So I'm fine with that.

**Pull request closed without merging**
