### PR TITLE
Fix some errors for Centos platform

### PR DESCRIPTION
**Pull request by velkoz1108**

### CODE REVIEW

**Comment by markjcrane** [comment]
Reviewed your changes and they are good. Please sign up as a contributor and I will accept your changes.
- https://github.com/fusionpbx/open-source/pulls

**Comment by markjcrane** [comment]
I just checked again to see if you had signed up as a contributor.
- https://github.com/fusionpbx/open-source

**Comment by velkoz1108** [comment]
Hello, I have created the PR(https://github.com/fusionpbx/open-source/pull/294)

**Comment by markjcrane** [comment]
Great I will accept your changes to the CentOS install

**Pull request merged**
