### PR TITLE
Fix to issue #76 - Use php5 for some dists with new command-line switch

### PR DESCRIPTION
**Pull request by erxspin**
Example usage
``
./install.sh --use-php5-package
``

### CODE REVIEW

**Comment by erxspin** [comment]
Issue #76 - ARM install now broken

Need to make some tests on ARM devices

**Comment by erxspin** [comment]
Recommited because of big typos

**Comment by erxspin** [comment]
Almost ready

**Comment by markjcrane** [comment]
+        LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
+        LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php5-compat

I don't see the purpose to adding new ppa for PHP 5? It's part of the standard operating system 's rep, please explain.

**Comment by DigiDaz** [comment]
The add-apt-repository thing seems to fail on raspberry pi anyway, some python problem or other, maybe add a debian php 7 eg:

printf "deb http://packages.moopi.uk/debian jessie main" > /etc/apt/sources.list.d/moopi.list
wget -O - http://packages.moopi.uk/debian/moopi.gpg.key | apt-key add -

With respect to the printf, I had a situation with a script where it was working for some people and not for others. The guys at #bash quickly nailed it and said echo is evil, use printf instead.

**Comment by erxspin** [comment]
> I don't see the purpose to adding new ppa for PHP 5? It's part of the standard operating system 's repo, please explain.

You are right.

It seems I wanted to add PPA not for Debian but for Ubuntu here ... Maybe I was just confused when doing tests in several places at once with two branches.

**Comment by erxspin** [comment]
> The add-apt-repository thing seems to fail on raspberry pi anyway, some python problem or other

So if we think there is no much need in "add-apt-repository" then we should throw it away from script.

**Comment by markjcrane** [comment]
Accepting this for now. 

Command line switches will be removed in the future in the main script. Replaced by config.sh where optionally a command line script could be used to write the config.sh.

**Pull request merged**
