### PR TITLE
Bug fix prepare installation with various package managers

### PR DESCRIPTION
**Pull request by erxspin**

### CODE REVIEW

**Comment by erxspin** [comment]
Be more compatible

**Comment by erxspin** [comment]
One can test it with following command

``wget -O - https://raw.githubusercontent.com/erxspin/fusionpbx-install.sh/devel/pre-install.sh | sh``

Tested under Debian 8.7 - works ok

**Comment by erxspin** [comment]
One can use curl instead of wget for FreeBSD

``curl https://raw.githubusercontent.com/erxspin/fusionpbx-install.sh/devel/pre-install.sh | sh``

Tested under FreeBSD 10.3 amd64 - work ok, updates all, installs git and fetches this repo succesfully

**Comment by erxspin** [comment]
Tested under CentOS 7.3 amd64 - work ok, updates all, installs git and fetches this repo succesfully

P.S. yum detected and used, no dnf

**Comment by markjcrane** [comment]
In FreeBSD the common alternative to use instead of wget is fetch.

I'm thinking about your idea of having the common pre-install.sh.

Alternative is the option to have a pre-install.sh for each operating system that we have an install for.
centos/pre-install.sh
debian/pre-install.sh
freebsd/pre-install.sh

**Comment by markjcrane** [comment]
What I don't like about the current pre-install.sh that you have built while it is a lot nicer than the old one. FusionPBX doesn't have many variables that are abbreviated typically spell out the word to make it easier on people that are not native English speakers. Variables are lower case and separated by and underscore between the words.

**Comment by erxspin** [comment]
Hmm ...
So if you have got an idea than you can use proposed approach in many other places ...

**Pull request closed without merging**
