### PR TITLE
fix appending crontab

### PR DESCRIPTION
**Pull request by chansizzle**

### CODE REVIEW

**Comment by chansizzle** [comment]
The other way to fix the error of "bash:  crontab -: command not found
no crontab for root
cat: /dev/fd/62 : No such file or directory"

is to ensure there are no non breaking spaces or other hidden characters in the command.
```
cat <(crontab -l) <(echo "* * * * * $(which php) /var/www/fusionpbx/app/xml_cdr/xml_cdr_import.php 300") | crontab -
```

**Comment by markjcrane** [comment]
- So you have installed bash on your server?
- What version of the OS are you using?

**Comment by markjcrane** [comment]
It seems to work with the dash - and with it on a default debian install. 
- https://www.computerhope.com/unix/ucrontab.htm
"Load the crontab data from the specified file. If file is a dash ("-"), the crontab data is read from [standard input](https://www.computerhope.com/jargon/s/stdin.htm)."

Still seems to work without the dash so it seems to be assumed.

**Comment by chansizzle** [comment]
new debian 11 install, running the download and install commands. Trying the command manually and via finish.sh both error until I 1) remove the dash ('-') at the end, or 2) remove and replace all of the spaces in the command (and include the desired dash). So it seems there is a bad space character somehow.

**Comment by markjcrane** [comment]
On my Debian 11 works both ways so for that reason I'll accept the change.

**Pull request merged**
